### ISSUE TITLE
Error running function via API

### ISSUE THREAD

**Issue by HughSt** [disarm-platform/fn-raster-vector-summary-stats#1]
@onlyjsmith 

I just updated the shiny UI to make a post request to 

https://faas.srv.disarm.io/function/fn-raster-vector-summary-stats

instead of

http://faas.srv.disarm.io/function/fn-raster-vector-summary-stats_0_0_5

and I get this error

Error: lexical error: invalid char in json text.
                                       Param `{key}` must be either tr
                     (right here) ------^

Any ideas what's going on?

**Comment by onlyjsmith** [comment]
That might be an error in the function, and it’s not returning JSON, but blurting out some text. Relates to another issue I just saw - the UIs don’t seem to be hunting for `result` property in what the server sends back. 

e.g. you make a request, and the server replies with something that looks like this:

```
{
	“function_status”: “success”,
	“result”: {...}
}
```
The `result` property is what would contain the GeoJSON FeatureCollection to stick on the map.

**Comment by HughSt** [comment]
You are right, we are not dealing with the response adequately, but amazingly R doesn't seem to throw and error when I create an sf object from the entire response (i.e. including function_status). I've corrected that. BTW - it is still returning `content` not `result`, i.e.

```
{
	“function_status”: “success”,
	“content”: {...}
}
``` 

Guessing this might be because you haven't updated the function on OpenFaaS with this latest version? 

However, that isn't the reason the function is giving me an error. If I pass (`geojson_out = "true"`) into the function I get this error

```
$function_status
[1] "error"

$content
[1] "Error from function: Param `{key}` must be either true or false (JSON boolean)"
```

If I remove it, it looks like it is defaulting to true in the function and it returns correctly. I've looked at the code, but I can't see where this check is occurring..

**Comment by onlyjsmith** [comment]
Have bumped version and redeployed the function - think you're right it was an older version

The `geojson_out` param should be a boolean. You're passing in a string (`"true"` rather than `True`). 

Also, `geojson_out` defaults to `true` anyway, so you shouldn't need to do this. (See [SPECS.md](https://github.com/disarm-platform/fn-raster-vector-summary-stats/blob/master/SPECS.md) ;-) )
