### ISSUE TITLE
close repo in favour of fn-raster-vector-summary-stats-enhanced

### ISSUE THREAD

**Issue by onlyjsmith** [disarm-platform/fn-raster-vector-summary-stats#7]
https://github.com/disarm-platform/fn-raster-vector-summary-stats-enhanced

The other repo has more functionality: works with a `buffer_km` parameter. We don't need both!

**Comment by HughSt** [comment]
Sure. When you say close - do you mean remove or archive?

**Comment by onlyjsmith** [comment]
For this one, probably _delete_ - to remove any confusion. They do basically the same thing, this one with buffering.
